/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFrameStockage.java
 *
 * Created on 7 nov. 2010, 18:01:01
 */

package portnantestp1.vue;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import portnantestp1.controleur.Matiere;
import portnantestp1.controleur.Ports;
import portnantestp1.controleur.ZoneStockage;
import portnantestp1.controleur.ZoneStockageD;

/**
 *
 * @author pierre
 */
public class jFrameStockage extends javax.swing.JFrame {

    /** Creates new form jFrameStockage */
    public jFrameStockage() {
        initComponents();
        this.setDefaultCloseOperation(jFrameStockage.DISPOSE_ON_CLOSE);

        lblTypeMat.setVisible(false);
        listTypeMatieres.setVisible(false);

        majListMatieres();
    }


    /*
     * Var
     */
    private ZoneStockage stockage;


    /*
     * Methodes principales
     */
    public void addFermerListener(ActionListener a)
    {
        btnFermer.addActionListener(a);
    }

    // Remplissage du tableau des matiere dangeureuse à partir du cmbBox
    private void getMatieresDangeureuse()
    {
        for(int i=0 ; i< listTypeMatieres.getSelectedValues().length ; i++)
        {
            String unType = (String)listTypeMatieres.getSelectedValues()[i];
            ((ZoneStockageD)stockage).addTypeDangers(unType);
        }
    }

    private void majListMatieres()
    {
        List<Matiere> lst = Ports.getListMatieres();
        DefaultListModel dlm = new DefaultListModel();
        for(int i=0 ; i<lst.size() ; i++)
        {
            dlm.addElement(lst.get(i).getNom());
        }
        listTypeMatieres.setModel(dlm);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTypeMat = new javax.swing.JLabel();
        checkBoxDangeureux = new javax.swing.JCheckBox();
        btnEnregistrer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTypeMatieres = new javax.swing.JList();
        txtBoxCapaMax = new javax.swing.JTextField();
        btnFermer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBoxNum = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Utopia", 1, 18));
        jLabel1.setText("Zone de Stockage");

        jLabel2.setFont(new java.awt.Font("Utopia", 0, 11));
        jLabel2.setText("Capacité Maximale");

        jLabel3.setFont(new java.awt.Font("Utopia", 0, 11));
        jLabel3.setText("Stockage Dangereux");

        lblTypeMat.setFont(new java.awt.Font("Utopia", 0, 11));
        lblTypeMat.setText("Types de matières dangeureuses");

        checkBoxDangeureux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDangeureuxActionPerformed(evt);
            }
        });

        btnEnregistrer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listTypeMatieres);

        txtBoxCapaMax.setFont(new java.awt.Font("Utopia", 0, 11)); // NOI18N

        btnFermer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Utopia", 0, 11)); // NOI18N
        jLabel4.setText("Numero");

        txtBoxNum.setFont(new java.awt.Font("Utopia", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxDangeureux))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypeMat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBoxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBoxCapaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFermer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnregistrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBoxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBoxCapaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(checkBoxDangeureux, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblTypeMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnEnregistrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFermer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxDangeureuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDangeureuxActionPerformed
        // TODO add your handling code here:

        if(checkBoxDangeureux.isSelected())
        {
            lblTypeMat.setVisible(true);
            listTypeMatieres.setVisible(true);
        }
        else
        {
            lblTypeMat.setVisible(false);
            listTypeMatieres.setVisible(false);
        }

    }//GEN-LAST:event_checkBoxDangeureuxActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        // TODO add your handling code here:

        if(txtBoxCapaMax.getText().isEmpty() || txtBoxNum.getText().isEmpty())
            return;

        try
        {
            int capa = Integer.parseInt(txtBoxCapaMax.getText());
            int num = Integer.parseInt(txtBoxNum.getText());
            if(capa > 0 && num>0)
            {
                if(Ports.getZoneStockage(num)!=null)
                    return;

                if(checkBoxDangeureux.isSelected() && listTypeMatieres.getSelectedValues().length > 0)
                {
                    stockage = new ZoneStockageD();
                    getMatieresDangeureuse();
                }
                else
                    stockage = new ZoneStockage();

                stockage.setCapaMax(capa);
                stockage.setCapaDispo(capa);
                stockage.setNum(num);
                Ports.ajoutZoneStockage(stockage);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Veuillez saisir une capacité entière positive");
        }
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameStockage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnFermer;
    private javax.swing.JCheckBox checkBoxDangeureux;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTypeMat;
    private javax.swing.JList listTypeMatieres;
    private javax.swing.JTextField txtBoxCapaMax;
    private javax.swing.JTextField txtBoxNum;
    // End of variables declaration//GEN-END:variables

}
