/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFrameMatiere.java
 *
 * Created on 23 nov. 2010, 01:08:48
 */

package portnantestp1.vue;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import portnantestp1.controleur.Matiere;
import portnantestp1.controleur.Ports;

/**
 *
 * @author pierre
 */
public class jFrameMatiere extends javax.swing.JFrame {

    /** Creates new form jFrameMatiere */
    public jFrameMatiere() {
        initComponents();
        this.setDefaultCloseOperation(jFrameStockage.DISPOSE_ON_CLOSE);

        //forme
        btnSupprimer.setEnabled(false);
    }

    // ################
    // Methodes
    // ################
    private void majMatieres()
    {
        List<Matiere> lst = Ports.getListMatieres();
        ((DefaultTableModel) jTableMatieres.getModel()).setRowCount(lst.size());
        
        /*for(int i=0 ; i<jTableMatieres.getRowCount() ; i++)
        {
            jTableMatieres.setValueAt(null, i, 0);
        }*/
        
        for(int i=0 ; i<lst.size() ; i++)
        {
            jTableMatieres.setValueAt(lst.get(i).getNom(), i, 0);
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatieres = new javax.swing.JTable();
        btnEnrg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMatiere = new javax.swing.JTextField();
        btnSupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Utopia", 1, 18));
        jLabel1.setText("Matières");

        jTableMatieres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMatieres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMatieresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMatieres);
        jTableMatieres.getColumnModel().getColumn(0).setResizable(false);

        btnEnrg.setText("Enregistrer");
        btnEnrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrgActionPerformed(evt);
            }
        });

        jLabel2.setText("Nouvelle Matière");

        txtMatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatiereActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnrg)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupprimer))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnSupprimer)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnEnrg)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        majMatieres();
    }//GEN-LAST:event_formWindowOpened

    private void txtMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatiereActionPerformed

    private void btnEnrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrgActionPerformed
        if(txtMatiere.getText().length()>2 && Ports.getMatiere(txtMatiere.getText())==null)
        {
            Ports.ajoutMatiere(txtMatiere.getText());
            majMatieres();
            txtMatiere.setText(null);
        }
}//GEN-LAST:event_btnEnrgActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        Ports.supprimeMatiere((String) (jTableMatieres.getValueAt(jTableMatieres.getSelectedRow(), 0)));
        majMatieres();
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void jTableMatieresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMatieresMouseClicked
        if(jTableMatieres.getSelectedRowCount()==1)
        {
            btnSupprimer.setEnabled(true);
        }
    }//GEN-LAST:event_jTableMatieresMouseClicked

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameMatiere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrg;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMatieres;
    private javax.swing.JTextField txtMatiere;
    // End of variables declaration//GEN-END:variables

}
