/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFrameStat.java
 *
 * Created on 24 nov. 2010, 00:13:28
 */

package portnantestp1.vue;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import portnantestp1.controleur.Ports;
import portnantestp1.controleur.Stats;

/**
 *
 * @author pierre
 */
public class jFrameStat extends javax.swing.JFrame {
    
    /*
     * Var
     */
    private Stats stat;


    /** Creates new form jFrameStat */
    public jFrameStat() {
        initComponents();
        this.setDefaultCloseOperation(jFrameStockage.DISPOSE_ON_CLOSE);

        // Initialisation des données
        majCmb();
        majActuel();

    }


    /*
     * Methodes Principales
     */
    private void majCmb()
    {
        List<Stats> lst = Ports.getListStats();
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        cmbBoxDate.setModel(dcbm);
        for(int i=0 ; i<lst.size() ; i++)
        {
            cmbBoxDate.addItem(lst.get(i).getDate());
        }
    }

    private void majActuel()
    {
        Stats st = new Stats();
        txtBoxActuelNavireDg.setText(st.getStatNavireDangereux().toString());
        txtBoxActuelNavireNonDg.setText(st.getStatNavire().toString());
        txtBoxActuelNavireTotal.setText(st.getStatTotal("Navire").toString());

        txtBoxActuelZoneDg.setText(st.getStatZoneDangereux().toString());
        txtBoxActuelZoneNonDg.setText(st.getStatZone().toString());
        txtBoxActuelZoneTotal.setText(st.getStatTotal("ZoneStockage").toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblText14 = new javax.swing.JLabel();
        txtBoxPonctuelNavireTotal = new javax.swing.JTextField();
        lblText15 = new javax.swing.JLabel();
        txtBoxPonctuelNavireNonDg = new javax.swing.JTextField();
        lblText16 = new javax.swing.JLabel();
        lblText18 = new javax.swing.JLabel();
        txtBoxPonctuelNavireDg = new javax.swing.JTextField();
        lblText28 = new javax.swing.JLabel();
        lblText17 = new javax.swing.JLabel();
        txtBoxPonctuelZoneNonDg = new javax.swing.JTextField();
        lblText29 = new javax.swing.JLabel();
        txtBoxPonctuelZoneDg = new javax.swing.JTextField();
        lblText30 = new javax.swing.JLabel();
        txtBoxPonctuelZoneTotal = new javax.swing.JTextField();
        cmbBoxDate = new javax.swing.JComboBox();
        btnAjouterStat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblText25 = new javax.swing.JLabel();
        lblText26 = new javax.swing.JLabel();
        lblText33 = new javax.swing.JLabel();
        txtBoxActuelNavireNonDg = new javax.swing.JTextField();
        txtBoxActuelNavireDg = new javax.swing.JTextField();
        txtBoxActuelNavireTotal = new javax.swing.JTextField();
        lblText27 = new javax.swing.JLabel();
        lblText34 = new javax.swing.JLabel();
        lblText35 = new javax.swing.JLabel();
        lblText36 = new javax.swing.JLabel();
        lblText37 = new javax.swing.JLabel();
        txtBoxActuelZoneNonDg = new javax.swing.JTextField();
        txtBoxActuelZoneDg = new javax.swing.JTextField();
        txtBoxActuelZoneTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Utopia", 1, 18));
        jLabel1.setText("Statistiques");

        jTabbedPane1.setFont(new java.awt.Font("Utopia", 1, 12)); // NOI18N

        lblText14.setFont(new java.awt.Font("Utopia", 1, 12));
        lblText14.setText("Navires");

        txtBoxPonctuelNavireTotal.setEditable(false);

        lblText15.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText15.setText("Non Dangeureux");

        txtBoxPonctuelNavireNonDg.setEditable(false);

        lblText16.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText16.setText("Total");

        lblText18.setFont(new java.awt.Font("Utopia", 1, 12));
        lblText18.setText("Zones de Stockage");

        txtBoxPonctuelNavireDg.setEditable(false);

        lblText28.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText28.setText("Dangeureux");

        lblText17.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText17.setText("Non Dangeureux");

        txtBoxPonctuelZoneNonDg.setEditable(false);

        lblText29.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText29.setText("Dangeureux");

        txtBoxPonctuelZoneDg.setEditable(false);

        lblText30.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText30.setText("Total");

        txtBoxPonctuelZoneTotal.setEditable(false);

        cmbBoxDate.setFont(new java.awt.Font("Utopia", 1, 11)); // NOI18N
        cmbBoxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxDateActionPerformed(evt);
            }
        });

        btnAjouterStat.setFont(new java.awt.Font("Utopia", 1, 11)); // NOI18N
        btnAjouterStat.setText("Ajouter");
        btnAjouterStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterStatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText14)
                    .addComponent(lblText18)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblText15)
                                            .addComponent(lblText28)
                                            .addComponent(lblText16))
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblText29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblText30, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(37, 37, 37))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblText17, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbBoxDate, 0, 165, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBoxPonctuelZoneTotal)
                            .addComponent(txtBoxPonctuelZoneDg)
                            .addComponent(txtBoxPonctuelZoneNonDg)
                            .addComponent(btnAjouterStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBoxPonctuelNavireTotal)
                            .addComponent(txtBoxPonctuelNavireNonDg)
                            .addComponent(txtBoxPonctuelNavireDg, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterStat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText15)
                    .addComponent(txtBoxPonctuelNavireNonDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxPonctuelNavireDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxPonctuelNavireTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText16))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblText18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblText17)
                        .addGap(11, 11, 11)
                        .addComponent(lblText29)
                        .addGap(11, 11, 11)
                        .addComponent(lblText30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBoxPonctuelZoneNonDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxPonctuelZoneDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxPonctuelZoneTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Ponctuelle", jPanel1);

        lblText25.setFont(new java.awt.Font("Utopia", 1, 12));
        lblText25.setText("Navires");

        lblText26.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText26.setText("Non Dangeureux");

        lblText33.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText33.setText("Dangeureux");

        txtBoxActuelNavireNonDg.setEditable(false);

        txtBoxActuelNavireDg.setEditable(false);

        txtBoxActuelNavireTotal.setEditable(false);

        lblText27.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText27.setText("Total");

        lblText34.setFont(new java.awt.Font("Utopia", 1, 12));
        lblText34.setText("Zones de Stockage");

        lblText35.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText35.setText("Non Dangeureux");

        lblText36.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText36.setText("Dangeureux");

        lblText37.setFont(new java.awt.Font("Utopia", 0, 11));
        lblText37.setText("Total");

        txtBoxActuelZoneNonDg.setEditable(false);

        txtBoxActuelZoneDg.setEditable(false);

        txtBoxActuelZoneTotal.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblText26)
                            .addComponent(lblText33)
                            .addComponent(lblText27))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBoxActuelNavireTotal)
                            .addComponent(txtBoxActuelNavireNonDg)
                            .addComponent(txtBoxActuelNavireDg, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblText35)
                            .addComponent(lblText36)
                            .addComponent(lblText37))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBoxActuelZoneTotal)
                            .addComponent(txtBoxActuelZoneNonDg)
                            .addComponent(txtBoxActuelZoneDg, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblText34))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText26)
                    .addComponent(txtBoxActuelNavireNonDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxActuelNavireDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxActuelNavireTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText27))
                .addGap(18, 18, 18)
                .addComponent(lblText34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText35)
                    .addComponent(txtBoxActuelZoneNonDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxActuelZoneDg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxActuelZoneTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText37))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Actuelle", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterStatActionPerformed
        stat = new Stats();
        Ports.ajoutObj(stat);
        majCmb();
}//GEN-LAST:event_btnAjouterStatActionPerformed

    private void cmbBoxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxDateActionPerformed
        Stats st = Ports.getStat((String) cmbBoxDate.getSelectedItem());

        txtBoxPonctuelNavireDg.setText(st.getStatNavireDangereux().toString());
        txtBoxPonctuelNavireNonDg.setText(st.getStatNavire().toString());
        txtBoxPonctuelNavireTotal.setText(st.getStatTotal("Navire").toString());

        txtBoxPonctuelZoneDg.setText(st.getStatZoneDangereux().toString());
        txtBoxPonctuelZoneNonDg.setText(st.getStatZone().toString());
        txtBoxPonctuelZoneTotal.setText(st.getStatTotal("ZoneStockage").toString());
}//GEN-LAST:event_cmbBoxDateActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameStat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterStat;
    private javax.swing.JComboBox cmbBoxDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblText14;
    private javax.swing.JLabel lblText15;
    private javax.swing.JLabel lblText16;
    private javax.swing.JLabel lblText17;
    private javax.swing.JLabel lblText18;
    private javax.swing.JLabel lblText25;
    private javax.swing.JLabel lblText26;
    private javax.swing.JLabel lblText27;
    private javax.swing.JLabel lblText28;
    private javax.swing.JLabel lblText29;
    private javax.swing.JLabel lblText30;
    private javax.swing.JLabel lblText33;
    private javax.swing.JLabel lblText34;
    private javax.swing.JLabel lblText35;
    private javax.swing.JLabel lblText36;
    private javax.swing.JLabel lblText37;
    private javax.swing.JTextField txtBoxActuelNavireDg;
    private javax.swing.JTextField txtBoxActuelNavireNonDg;
    private javax.swing.JTextField txtBoxActuelNavireTotal;
    private javax.swing.JTextField txtBoxActuelZoneDg;
    private javax.swing.JTextField txtBoxActuelZoneNonDg;
    private javax.swing.JTextField txtBoxActuelZoneTotal;
    private javax.swing.JTextField txtBoxPonctuelNavireDg;
    private javax.swing.JTextField txtBoxPonctuelNavireNonDg;
    private javax.swing.JTextField txtBoxPonctuelNavireTotal;
    private javax.swing.JTextField txtBoxPonctuelZoneDg;
    private javax.swing.JTextField txtBoxPonctuelZoneNonDg;
    private javax.swing.JTextField txtBoxPonctuelZoneTotal;
    // End of variables declaration//GEN-END:variables

}
